<a href="https://colab.research.google.com/github/p-sachin/huggingface_nlp_tutorials/blob/main/using_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 58.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 19.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 79.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.6 MB/s eta 0:00:00


**Building the transformer pipeline**

In [ ]:
from transformers import pipeline

In [ ]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
classifier(['Hello I am very happy today!', "Go kill yourself.", "I am really mad at you.", "I like you a lot because you are a nice person."])

[{'label': 'POSITIVE', 'score': 0.9998555183410645},
 {'label': 'NEGATIVE', 'score': 0.9993353486061096},
 {'label': 'NEGATIVE', 'score': 0.9984453320503235},
 {'label': 'POSITIVE', 'score': 0.9998695850372314}]

<img src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter2/full_nlp_pipeline.svg" align="center">

In [ ]:
# Preprocessing with Tokenizer
# Like other neural networks, Transformer models can’t process raw text directly, so the first step of our pipeline is to convert the text inputs into numbers that the model can make sense of. 
#To do this we use a tokenizer, which will be responsible for:
# Splitting the input into words, subwords, or symbols (like punctuation) that are called tokens
# Mapping each token to an integer
# Adding additional inputs that may be useful to the model
from transformers import AutoTokenizer

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

raw_inputs = ['Hello I am very happy today!', "Go kill yourself.", "I am really mad at you.", "I like you a lot because you are a nice person."]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='tf')

In [ ]:
from transformers import TFAutoModel

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
model = TFAutoModel.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertModel: ['pre_classifier', 'dropout_19', 'classifier']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [ ]:
output = model(inputs)

In [ ]:
output.last_hidden_state.shape

TensorShape([4, 14, 768])

In [ ]:
from transformers import TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_97']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(inputs)

In [ ]:
outputs.logits.shape

TensorShape([4, 2])

In [ ]:
import tensorflow as tf
predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor(
[[1.4440547e-04 9.9985552e-01]
 [9.9933535e-01 6.6461449e-04]
 [9.9844533e-01 1.5547128e-03]
 [1.3039388e-04 9.9986959e-01]], shape=(4, 2), dtype=float32)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [4]:
# Creating a transformer
from transformers import BertConfig, TFBertModel

# Building the config
config = BertConfig()

In [5]:
print(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.26.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [7]:
model = TFBertModel.from_pretrained("bert-base-cased")

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [10]:
model.save_pretrained("code")

In [11]:
ls code

config.json  tf_model.h5


In [12]:
sequences = ["Hello!", "Cool.", "Nice!"]

In [13]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [14]:
import tensorflow as tf

model_inputs = tf.constant(encoded_sequences)

In [15]:
output = model(model_inputs)

In [16]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
array([[[ 4.4495744e-01,  4.8276314e-01,  2.7797154e-01, ...,
         -5.4032914e-02,  3.9393461e-01, -9.4769791e-02],
        [ 2.4942887e-01, -4.4093004e-01,  8.1772333e-01, ...,
         -3.1916580e-01,  2.2992226e-01, -4.1171610e-02],
        [ 1.3667595e-01,  2.2517839e-01,  1.4501980e-01, ...,
         -4.6915002e-02,  2.8224239e-01,  7.5565659e-02],
        [ 1.1788859e+00,  1.6738573e-01, -1.8187132e-01, ...,
          2.4671295e-01,  1.0440763e+00, -6.1964341e-03]],

       [[ 3.6435840e-01,  3.2463633e-02,  2.0257667e-01, ...,
          6.0110666e-02,  3.2451269e-01, -2.0996008e-02],
        [ 7.1865952e-01, -4.8725206e-01,  5.1740396e-01, ...,
         -4.4011983e-01,  1.4553036e-01, -3.7544779e-02],
        [ 3.3223242e-01, -2.3270920e-01,  9.4875932e-02, ...,
         -2.5268176e-01,  3.2171953e-01,  8.1105344e-04],
        [ 1.2523217e+00,  3.5754317e-01,

Tokenizers are one of the core components of the NLP pipeline. They serve one purpose: to translate text into data that can be processed by the model. Models can only process numbers, so tokenizers need to convert our text inputs to numerical data. In this section, we’ll explore exactly what happens in the tokenization pipeline.

In [3]:
# Tokenizers
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
sequence = "I am using a transformer modelization and it is simple."
tokens = tokenizer.tokenize(sequence)

In [7]:
tokens

['I',
 'am',
 'using',
 'a',
 'transform',
 '##er',
 'model',
 '##ization',
 'and',
 'it',
 'is',
 'simple',
 '.']

In [9]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [11]:
print(ids)

[146, 1821, 1606, 170, 11303, 1200, 2235, 2734, 1105, 1122, 1110, 3014, 119]


In [14]:
ids

[146, 1821, 1606, 170, 11303, 1200, 2235, 2734, 1105, 1122, 1110, 3014, 119]

In [12]:
another_sequence = "I’ve been waiting for a HuggingFace course my whole life."
print(tokenizer.convert_tokens_to_ids(tokenizer.tokenize(another_sequence)))

[146, 787, 1396, 1151, 2613, 1111, 170, 20164, 10932, 2271, 7954, 1736, 1139, 2006, 1297, 119]


In [13]:
next_sequence = "I hate this so much!"
print(tokenizer.convert_tokens_to_ids(tokenizer.tokenize(next_sequence)))

[146, 4819, 1142, 1177, 1277, 106]


In [22]:
# Decoding
decoded_string = tokenizer.decode([146, 787, 1396, 1151, 2613, 1111, 170, 20164, 10932, 2271, 7954, 1736, 1139, 2006, 1297, 119])
decoded_string

'I ’ ve been waiting for a HuggingFace course my whole life.'

In [4]:
# Handling Multiple Sequences Together (Batch Inputs)
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [72]:
sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)


In [43]:

input_ids = tf.constant([[200,400,600], [100,500, tokenizer.pad_token_id]])

In [34]:
input_ids

<tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
         2607,  2026,  2878,  2166,  1012],
       [ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
         2607,  2026,  2878,  2166,  1012]], dtype=int32)>

In [35]:
output = model(input_ids)

In [36]:
output.logits

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.727621 ,  2.878938 ],
       [-2.7276204,  2.878937 ]], dtype=float32)>

In [55]:
# Try it out applying tokenization manually on two sentences
try_sequence = ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
# Tokenize the sequences
tokenized_sequence = [tokenizer.tokenize(seq) for seq in try_sequence]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokenized_sequence]

In [60]:
# Pad the sequences so they have the same length
max_length = max([len(seq) for seq in ids])
padded_input_ids = [seq + [tokenizer.pad_token_id] * (max_length - len(seq)) for seq in ids]

In [61]:
padded_input_ids

[[1045,
  1005,
  2310,
  2042,
  3403,
  2005,
  1037,
  17662,
  12172,
  2607,
  2026,
  2878,
  2166,
  1012],
 [1045, 5223, 2023, 2061, 2172, 999, 0, 0, 0, 0, 0, 0, 0, 0]]

In [62]:
print(model(tf.constant(sequence_id1)).logits)
print(model(tf.constant(sequence_id2)).logits)
print(model(tf.constant(padded_input_ids)).logits)

tf.Tensor([[-2.7276213  2.878938 ]], shape=(1, 2), dtype=float32)
tf.Tensor([[ 3.193092  -2.6685228]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[-2.72762    2.8789363]
 [ 2.5423343 -2.126485 ]], shape=(2, 2), dtype=float32)


In [28]:
attention_mask = [
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [1,1,1,1,1,1,0,0,0,0,0,0,0,0]
]

In [29]:
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]

In [64]:
outputs = model(tf.constant(padded_input_ids), attention_mask=tf.constant(attention_mask))

In [65]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.72762  ,  2.8789363],
       [ 3.1930926, -2.668524 ]], dtype=float32)>, hidden_states=None, attentions=None)

**Putting it all together**

In [66]:
from transformers import AutoTokenizer

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [73]:
sequence = ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
model_inputs = tokenizer(sequence)

In [74]:
model_inputs

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 1045, 5223, 2023, 2061, 2172, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [81]:
model_inputs = tokenizer(sequence, truncation=True)
model_inputs

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 1045, 5223, 2023, 2061, 2172, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [79]:
model_inputs = tokenizer(sequence, padding=True)
model_inputs

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 1045, 5223, 2023, 2061, 2172, 999, 102, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}

In [82]:
# Return as a tensor or numpy array 
model_inputs = tokenizer(sequence, padding=True, return_tensors='tf')
model_inputs

In [84]:
# Return as a tensor or numpy array 
model_inputs = tokenizer(sequence, padding=True, return_tensors='np')
model_inputs

{'input_ids': array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,
            0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [86]:
tokenizer.decode(model_inputs['input_ids'][0])

"[CLS] i've been waiting for a huggingface course my whole life. [SEP]"

In [87]:
# From tokenizer to model
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]


Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [88]:
tokens = tokenizer(sequence, padding=True, truncation=True, return_tensors='tf')


In [90]:
output = model(**tokens)

In [91]:
output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.560697 ,  1.6122822],
       [ 4.1692314, -3.3464477]], dtype=float32)>, hidden_states=None, attentions=None)