<a href="https://colab.research.google.com/github/p-sachin/huggingface_nlp_tutorials/blob/main/using_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 47.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 95.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 22.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 47.1 MB/s eta 0:00:00


**Building the transformer pipeline**

In [ ]:
from transformers import pipeline

In [ ]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [ ]:
classifier(['Hello I am very happy today!', "Go kill yourself.", "I am really mad at you.", "I like you a lot because you are a nice person."])

[{'label': 'POSITIVE', 'score': 0.9998555183410645},
 {'label': 'NEGATIVE', 'score': 0.9993353486061096},
 {'label': 'NEGATIVE', 'score': 0.9984453320503235},
 {'label': 'POSITIVE', 'score': 0.9998695850372314}]

<img src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter2/full_nlp_pipeline.svg" align="center">

In [ ]:
# Preprocessing with Tokenizer
# Like other neural networks, Transformer models can’t process raw text directly, so the first step of our pipeline is to convert the text inputs into numbers that the model can make sense of. 
#To do this we use a tokenizer, which will be responsible for:
# Splitting the input into words, subwords, or symbols (like punctuation) that are called tokens
# Mapping each token to an integer
# Adding additional inputs that may be useful to the model
from transformers import AutoTokenizer

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

raw_inputs = ['Hello I am very happy today!', "Go kill yourself.", "I am really mad at you.", "I like you a lot because you are a nice person."]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='tf')

In [ ]:
from transformers import TFAutoModel

checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
model = TFAutoModel.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertModel: ['pre_classifier', 'dropout_19', 'classifier']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [ ]:
output = model(inputs)

In [ ]:
output.last_hidden_state.shape

TensorShape([4, 14, 768])

In [ ]:
from transformers import TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_97']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(inputs)

In [ ]:
outputs.logits.shape

TensorShape([4, 2])

In [ ]:
import tensorflow as tf
predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor(
[[1.4440547e-04 9.9985552e-01]
 [9.9933535e-01 6.6461449e-04]
 [9.9844533e-01 1.5547128e-03]
 [1.3039388e-04 9.9986959e-01]], shape=(4, 2), dtype=float32)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [4]:
# Creating a transformer
from transformers import BertConfig, TFBertModel

# Building the config
config = BertConfig()

In [5]:
print(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.26.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [7]:
model = TFBertModel.from_pretrained("bert-base-cased")

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [10]:
model.save_pretrained("code")

In [11]:
ls code

config.json  tf_model.h5


In [12]:
sequences = ["Hello!", "Cool.", "Nice!"]

In [13]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [14]:
import tensorflow as tf

model_inputs = tf.constant(encoded_sequences)

In [15]:
output = model(model_inputs)

In [16]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
array([[[ 4.4495744e-01,  4.8276314e-01,  2.7797154e-01, ...,
         -5.4032914e-02,  3.9393461e-01, -9.4769791e-02],
        [ 2.4942887e-01, -4.4093004e-01,  8.1772333e-01, ...,
         -3.1916580e-01,  2.2992226e-01, -4.1171610e-02],
        [ 1.3667595e-01,  2.2517839e-01,  1.4501980e-01, ...,
         -4.6915002e-02,  2.8224239e-01,  7.5565659e-02],
        [ 1.1788859e+00,  1.6738573e-01, -1.8187132e-01, ...,
          2.4671295e-01,  1.0440763e+00, -6.1964341e-03]],

       [[ 3.6435840e-01,  3.2463633e-02,  2.0257667e-01, ...,
          6.0110666e-02,  3.2451269e-01, -2.0996008e-02],
        [ 7.1865952e-01, -4.8725206e-01,  5.1740396e-01, ...,
         -4.4011983e-01,  1.4553036e-01, -3.7544779e-02],
        [ 3.3223242e-01, -2.3270920e-01,  9.4875932e-02, ...,
         -2.5268176e-01,  3.2171953e-01,  8.1105344e-04],
        [ 1.2523217e+00,  3.5754317e-01,